app:
  discord_api:
    # This is your application token. You get it from "https://discord.com/developers/applications"
    token:
    shard_count: 1
    # If shard_id is empty, it will be handled as 'None'
    shard_id:
  
  logging:
    activate: true
    level: "INFO"
  
  # WIP. Disregard!
  webserver:
    url: "https://localhost"
    port: 443